(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
  const money=n=>`৳ ${Number(n||0).toLocaleString('bn-BD')}`;
  const months=['জানুয়ারি','ফেব্রুয়ারি','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টেম্বর','অক্টোবর','নভেম্বর','ডিসেম্বর'];
  const validMobile=v=>/^01\d{9}$/.test(String(v||'').replace(/[\s-]/g,''));
  const normalizeMobile=v=>String(v||'').replace(/[\s-]/g,'');
  const cfg=window.MEMBER_SUPABASE_URL&&window.MEMBER_SUPABASE_ANON_KEY&& !window.MEMBER_SUPABASE_URL.includes('YOUR-NEW-PROJECT');
  const sb=cfg&&window.supabase?window.supabase.createClient(window.MEMBER_SUPABASE_URL,window.MEMBER_SUPABASE_ANON_KEY):null;
  let currentProfile=null;
  function msg(text,ok=false,id='authMsg'){const el=$(id);if(!el)return;el.textContent=text;el.className='message '+(ok?'success':'error');}
  function toggle(mode){const signup=mode==='signup';$('signupForm').hidden=!signup;$('loginForm').hidden=signup;$('showSignup').classList.toggle('active',signup);$('showLogin').classList.toggle('active',!signup);$('authTitle').textContent=signup?'সদস্য অ্যাকাউন্ট তৈরি':'সদস্য লগইন';$('authSubtitle').textContent=signup?'নাম, ঠিকানা ও মোবাইল নম্বর দিয়ে অ্যাকাউন্ট তৈরি করুন।':'অনুমোদিত সদস্যরা মোবাইল নম্বর ও পাসওয়ার্ড দিয়ে প্রবেশ করুন।';$('authMsg').textContent='';}
  function showOnly(which){$('authCard').hidden=which!=='auth';$('pendingCard').hidden=which!=='pending';$('dashboard').hidden=which!=='dashboard';}
  async function signUp(e){e.preventDefault();if(!sb){msg('নতুন আলাদা Supabase project এখনো যুক্ত করা হয়নি। Setup নির্দেশনা অনুসরণ করে config বসাতে হবে।');return;}const f=new FormData(e.currentTarget),name=String(f.get('full_name')||'').trim(),address=String(f.get('address')||'').trim(),mobile=normalizeMobile(f.get('mobile')),password=String(f.get('password')||'');if(name.length<2||address.length<2){msg('নাম ও ঠিকানা সঠিকভাবে দিন।');return}if(!validMobile(mobile)){msg('সঠিক ১১ সংখ্যার মোবাইল নম্বর দিন।');return}if(password.length<6){msg('পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।');return}msg('অ্যাকাউন্ট তৈরি হচ্ছে...',true);const {data,error}=await sb.auth.signUp({phone:'+88'+mobile,password});if(error){msg(error.message);return}const uid=data.user?.id;if(!uid){msg('অ্যাকাউন্ট তৈরি হয়েছে, কিন্তু ব্যবহারকারী আইডি পাওয়া যায়নি।');return}const {error:pe}=await sb.from('member_profiles').insert({id:uid,full_name:name,address,mobile,status:'pending'});if(pe){await sb.auth.signOut();msg(pe.message);return}await sb.auth.signOut();e.currentTarget.reset();toggle('login');msg('অ্যাকাউন্ট তৈরি হয়েছে। অ্যাডমিন অনুমোদনের পর লগইন করতে পারবেন।',true);}
  async function signIn(e){e.preventDefault();if(!sb){msg('নতুন আলাদা Supabase project এখনো যুক্ত করা হয়নি। Setup নির্দেশনা অনুসরণ করে config বসাতে হবে।');return;}const f=new FormData(e.currentTarget),mobile=normalizeMobile(f.get('mobile')),password=String(f.get('password')||'');if(!validMobile(mobile)){msg('সঠিক ১১ সংখ্যার মোবাইল নম্বর দিন।');return}msg('লগইন হচ্ছে...',true);const {data,error}=await sb.auth.signInWithPassword({phone:'+88'+mobile,password});if(error){msg(error.message);return}await loadSession();}
  async function loadSession(){const {data:{session}}=await sb.auth.getSession();if(!session?.user){showOnly('auth');return}const {data,error}=await sb.from('member_profiles').select('*').eq('id',session.user.id).maybeSingle();if(error||!data){await sb.auth.signOut();msg('সদস্য প্রোফাইল পাওয়া যায়নি।');showOnly('auth');return}currentProfile=data;if(data.status!=='approved'){showOnly('pending');return}showOnly('dashboard');$('memberName').textContent=data.full_name;$('memberMobile').textContent=data.mobile;$('memberProfile').innerHTML=`<div class="profile-item"><span>নাম</span><strong>${esc(data.full_name)}</strong></div><div class="profile-item"><span>ঠিকানা</span><strong>${esc(data.address)}</strong></div><div class="profile-item"><span>মোবাইল</span><strong>${esc(data.mobile)}</strong></div><div class="profile-item"><span>অবস্থা</span><strong>অনুমোদিত</strong></div>`;await loadDashboard();}
  async function getVisibility(){
    const {data,error}=await sb.from('member_visibility_settings').select('all_members_public').eq('id',true).maybeSingle();
    if(error) return false;
    return !!data?.all_members_public;
  }
  async function setVisibility(isPublic){
    const {error}=await sb.from('member_visibility_settings').update({all_members_public:!!isPublic,updated_at:new Date().toISOString()}).eq('id',true);
    if(error){msg(error.message,false,'adminMsg');return;}
    msg(isPublic?'সকল অনুমোদিত সদস্যের অ্যাকাউন্ট দেখা এখন Public করা হয়েছে।':'সকল সদস্যের অ্যাকাউন্ট Hide করা হয়েছে।',true,'adminMsg');
    await loadPending();
  }
  window.memberSetPublic=()=>setVisibility(true);
  window.memberSetHide=()=>setVisibility(false);
  async function loadDashboard(){const {data,error}=await sb.rpc('member_dashboard',{p_member_id:currentProfile.member_id});if(error){$('personalAccount').innerHTML='<div class="empty-state">ব্যক্তিগত হিসাবের RPC এখনো নতুন Supabase project-এ চালু করা হয়নি। Setup SQL চালানোর পর এখানে হিসাব আসবে।</div>';return;}const d=data||{};const s=d.summary||{};$('personalSummary').innerHTML=`<article><span>সকল বছরের মোট পরিশোধ</span><strong>${money(s.total_paid)}</strong></article><article><span>সকল বছরের মোট বাকি</span><strong>${money(s.total_due)}</strong></article><article><span>সদস্যের অবস্থা</span><strong>অনুমোদিত</strong></article>`;const rows=(d.months||[]).map(x=>`<tr><td>${esc(x.year)}</td><td>${months[Number(x.month)-1]||x.month}</td><td>${money(x.paid)}</td><td>${money(x.due)}</td></tr>`).join('');$('personalAccount').innerHTML=`<div class="table-wrap"><table><thead><tr><th>সাল</th><th>মাস</th><th>পরিশোধ</th><th>বাকি</th></tr></thead><tbody>${rows||'<tr><td colspan="4">কোনো হিসাব পাওয়া যায়নি</td></tr>'}</tbody></table></div>`;const org=d.organization||{};const publicAll=await getVisibility();$('organizationSummary').innerHTML=`<div class="summary-grid"><article><span>সদস্য হিসাব দৃশ্যমানতা</span><strong>${publicAll?'Public':'Hide'}</strong></article><article><span>সদস্য সংখ্যা</span><strong>${Number(org.member_count||0).toLocaleString('bn-BD')}</strong></article><article><span>মোট পরিশোধ</span><strong>${money(org.total_paid)}</strong></article><article><span>মোট লভ্যাংশ</span><strong>${money(org.total_profit)}</strong></article><article><span>মোট খরচ</span><strong>${money(org.total_expense)}</strong></article></div>`;}
  async function logout(){if(sb)await sb.auth.signOut();currentProfile=null;showOnly('auth');toggle('login');}
  async function adminLogin(e){e.preventDefault();if(!sb){msg('নতুন Supabase project config দিন।','adminMsg');return;}const f=new FormData(e.currentTarget),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){msg(error.message,false,'adminMsg');return}const {data:au,error:ae}=await sb.from('member_admins').select('user_id').eq('user_id',data.user.id).maybeSingle();if(ae||!au){await sb.auth.signOut();msg('এই অ্যাকাউন্টে অ্যাডমিন অনুমতি নেই।',false,'adminMsg');return}e.currentTarget.hidden=true;await loadPending();}
  async function loadPending(){const box=$('pendingMembers');box.hidden=false;const publicAll=await getVisibility();const controls=`<div class="visibility-controls"><div><b>সকল সদস্যের হিসাব:</b> <strong>${publicAll?'Public':'Hide'}</strong></div><div><button class="small-btn approve" onclick="window.memberSetPublic()">🟢 সকলের হিসাব Public</button> <button class="small-btn reject" onclick="window.memberSetHide()">🔴 সকলের হিসাব Hide</button></div></div>`;const {data,error}=await sb.from('member_profiles').select('id,member_id,full_name,address,mobile,created_at,status').eq('status','pending').order('created_at',{ascending:true});if(error){msg(error.message,false,'adminMsg');return}box.innerHTML=controls+`<table><thead><tr><th>নাম</th><th>ঠিকানা</th><th>মোবাইল</th><th>তারিখ</th><th>অ্যাকশন</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td class="name">${esc(x.address)}</td><td>${esc(x.mobile)}</td><td>${new Date(x.created_at).toLocaleDateString('bn-BD')}</td><td><button class="small-btn approve" onclick="window.memberApprove('${x.id}')">অনুমোদন</button> <button class="small-btn reject" onclick="window.memberReject('${x.id}')">বাতিল</button></td></tr>`).join('')||'<tr><td colspan="5">কোনো Pending account নেই</td></tr>'}</tbody></table>`;}
  async function setStatus(id,status){const {error}=await sb.from('member_profiles').update({status,approved_at:status==='approved'?new Date().toISOString():null}).eq('id',id).eq('status','pending');if(error){msg(error.message,false,'adminMsg');return}await loadPending();}
  window.memberApprove=id=>setStatus(id,'approved');window.memberReject=id=>setStatus(id,'rejected');
  $('showSignup').onclick=()=>toggle('signup');$('showLogin').onclick=()=>toggle('login');$('signupForm').onsubmit=signUp;$('loginForm').onsubmit=signIn;$('memberLogout').onclick=logout;$('pendingLogout').onclick=logout;$('adminLoginForm').onsubmit=adminLogin;$('footerYear').textContent=new Date().getFullYear();
  if(location.hash==='#admin')$('adminPanel').hidden=false; else $('adminPanel').hidden=true;
  if(!sb){msg('প্রস্তুত করা হয়েছে, কিন্তু নতুন Supabase project-এর URL ও key বসানো না হওয়া পর্যন্ত Login/Signup চালু হবে না।',false);}
  else loadSession();
})();
